- hosts: localhost
  become: true
  tasks:
    - name: Install required Python packages
      pip:
        name:
            - docker
            - requests
        executable: /Library/Frameworks/Python.framework/Versions/3.14/bin/pip3

    - name: Pull Docker image
      community.docker.docker_image:
        name: svrma13/scientific-calculator:latest
        source: pull

    - name: Stop old container if exists
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run container
      community.docker.docker_container:
        name: scientific-calculator
        image: svrma13/scientific-calculator:latest
        state: started
        interactive: true
        tty: true
        ports:
          - "8081:8080"