---
- name: Deploy Scientific Calculator
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Pull Docker image from DockerHub
      community.docker.docker_image:
        name: svrma13/scientific-calculator:latest
        source: pull

    - name: Stop existing container if running
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run Docker container
      community.docker.docker_container:
        name: scientific-calculator
        image: svrma13/scientific-calculator:latest
        state: started
        ports:
          - "8081:8080"
        restart_policy: always